import { SocketProvider } from '@/components/SocketContext'
import './globals.css'
import PostModal from '@/components/Posts/PostModal'

export const metadata = {
  title: 'Social Media',
  description: 'Generated by Social Media',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
  
    <html lang="vi">
      <body>
        <SocketProvider>
        {children}
        <PostModal/>
        </SocketProvider>
        </body>
    </html>
  )
}
