import { SocketProvider } from '@/components/SocketContext'
import './globals.css'


export const metadata = {
  title: 'VTC Media',
  description: 'Generated by VTC Media',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
  
    <html lang="vi">
      <body>
        <SocketProvider>
        {children}

        </SocketProvider>
        </body>
    </html>
  )
}
